### ISSUE TITLE
unauthorized_client An unauthorized client tried to access your resources.

### ISSUE THREAD

**Issue by vkaracic** [openedx-unsupported/ecommerce#351]
I keep getting this issue:
`unauthorized_client An unauthorized client tried to access your resources.` 

When I go login to Otto it redirects me to the LMS login which redirects me to:
`http://127.0.0.1:8000/oauth2/authorize/confirm`
where I get that error.

**Comment by clintonb** [comment]
@vkaracic see comment in #352. Also, if you are using a `private.py` settings file, make sure you are loading `get_lms_url` from the correct location. That function was recently moved.

**Comment by vkaracic** [comment]
I'm still getting the same error. This is my OAuth2 client data:
http://i.imgur.com/bmqraWZ.png
This is my local.py:
https://gist.github.com/vkaracic/5cc21f6174bf3965a276

`get_lms_url` seems to be loading from the correct location.

**Comment by clintonb** [comment]
Replace https with http.

Clinton Blackburn

**Comment by vkaracic** [comment]
Still getting the same error.

**Comment by clintonb** [comment]
Are you accessing your ecommerce service from http://localhost:8002 or http://127.0.0.1:8002? You need to use localhost since that is what you have set up for OAuth.

**Comment by vkaracic** [comment]
Correct, that solves the issue.
Thanks a lot!

**Comment by clintonb** [comment]
I prefer to use pseudo-hosts (made by editing `/etc/hosts`) to avoid this issue. My preference is ecommerce.local and lms.local.
